[package]
name = "splash"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
colored = "2.1.0"
lazy_static = "1.4.0"
notify = "6.1.1"
regex = "1.10.2"
