[package]
name = "splash"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1.0"
lazy_static = "1.4.0"
notify = "8.2.0"
regex = "1.10.2"
