[package]
name = "splash"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
colored = "3.1.1"
dirs = "6.0"
lazy_static = "1.5.0"
notify = "8.2.0"
regex = "1.12.2"

[dev-dependencies]
tempfile = "3.25"
